import { app } from "electron";
import { copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { readZaicodeLauncherPreferences, setZaicodeSplashEnabled, writeZaicodeLauncherPreferences } from "./zaicodeLauncherPreferences.js";

/**
 * Custom start-up splash picture (SRC-049): the operator picks one picture in
 * Settings and every start-up surface uses it - the root launcher's splash,
 * the app's own splash window and the in-window loading shell. The picture is
 * COPIED here (userData/zaicode-splash/) next to a generated splash.html, so
 * the bundled build never changes and a moved/deleted source file cannot break
 * the start-up. The generated page is the twin of build/zaicode-splash/splash.html.
 */

const IMAGE_MAGIC: readonly [string, string][] = [
  ["image/png", "png"],
  ["image/jpeg", "jpg"],
  ["image/gif", "gif"],
  ["image/webp", "webp"],
  ["image/bmp", "bmp"],
];

export function zaicodeSplashCustomDir(): string {
  return join(app.getPath("userData"), "zaicode-splash");
}

/** The custom dir only counts when it holds both its page and its picture. */
export function hasZaicodeCustomSplash(): boolean {
  return existsSync(join(zaicodeSplashCustomDir(), "zaicode-splash.html")) && customImageFile() !== null;
}

function customImageFile(): string | null {
  for (const entry of readdirSync(zaicodeSplashCustomDir())) {
    if (/^custom\.(png|jpg|jpeg|gif|webp|bmp)$/i.test(entry)) return join(zaicodeSplashCustomDir(), entry);
  }
  return null;
}

function sniffImage(bytes: Buffer): string | null {
  for (const [mime, ext] of IMAGE_MAGIC) {
    if (mime === "image/png" && bytes.length > 8 && bytes[0] === 0x89 && bytes[1] === 0x50) return ext;
    if (mime === "image/jpeg" && bytes.length > 3 && bytes[0] === 0xff && bytes[1] === 0xd8) return ext;
    if (mime === "image/gif" && bytes.subarray(0, 3).toString("latin1") === "GIF") return ext;
    if (mime === "image/webp" && bytes.subarray(0, 4).toString("latin1") === "RIFF" && bytes.subarray(8, 12).toString("latin1") === "WEBP") return ext;
    if (mime === "image/bmp" && bytes.subarray(0, 2).toString("latin1") === "BM") return ext;
  }
  return null;
}

const SPLASH_PAGE = (imageFile: string) => `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      http-equiv="Content-Security-Policy"
      content="default-src 'none'; img-src 'self'; style-src 'unsafe-inline'; script-src 'unsafe-inline'"
    />
    <title>ZAICODE</title>
    <!--
      ZAICODE custom start-up splash (SRC-049), generated by zaicodeSplashPrefs.ts
      next to the operator's own picture; the bundled twin lives in
      build/zaicode-splash/splash.html.
    -->
    <style>
      html,
      body {
        margin: 0;
        width: 560px;
        height: 300px;
        overflow: hidden;
        background: #1a1810;
        cursor: default;
        user-select: none;
        -webkit-app-region: drag;
      }
      img {
        display: block;
        width: 560px;
        height: 300px;
      }
      #status {
        position: fixed;
        left: 14px;
        right: 14px;
        top: 274px;
        height: 14px;
        display: flex;
        justify-content: space-between;
        gap: 8px;
        overflow: hidden;
        white-space: nowrap;
        font: 11px/14px "Verdana_m1", Verdana, sans-serif;
        color: #d4c89a;
        -webkit-font-smoothing: none;
      }
      #version {
        color: #9c9371;
      }
    </style>
  </head>
  <body>
    <img src="${imageFile}" alt="" />
    <div id="status"><span id="text">Starting ZAICODE…</span><span id="version">ZAICODE</span></div>
    <script>
      const version = new URLSearchParams(location.search).get("v");
      if (version) document.getElementById("version").textContent = "ZAICODE " + version;
      window.zaicodeSplashStatus = (text) => {
        document.getElementById("text").textContent = String(text);
      };
    </script>
  </body>
</html>
`;

export interface ZaicodeSplashPrefsState {
  enabled: boolean;
  hasCustom: boolean;
  customDataUrl: string | null;
}

function readState(): ZaicodeSplashPrefsState {
  const preferences = readZaicodeLauncherPreferences();
  const hasCustom = hasZaicodeCustomSplash();
  let customDataUrl: string | null = null;
  const file = hasCustom ? customImageFile() : null;
  if (file) {
    const bytes = readFileSync(file);
    const ext = /\.(\w+)$/.exec(file)?.[1]?.toLowerCase();
    const mime = ext === "jpg" ? "image/jpeg" : `image/${ext ?? "png"}`;
    customDataUrl = `data:${mime};base64,${bytes.toString("base64")}`;
  }
  return { enabled: preferences.splashEnabled, hasCustom, customDataUrl };
}

/** Reads the splash preferences for the settings page (the data URL previews the picture). */
export function readZaicodeSplashPrefs(): ZaicodeSplashPrefsState {
  return readState();
}

/**
 * Persists the splash preferences: the enabled flag, and a picture picked by
 * path (copied in) or `null` to return to the bundled picture. Returns the new
 * state; a bad picture leaves everything unchanged.
 */
export function setZaicodeSplashPrefs(input: { enabled: boolean; imagePath?: string | null }): ZaicodeSplashPrefsState {
  setZaicodeSplashEnabled(input.enabled);
  if (input.imagePath === null) {
    if (readZaicodeLauncherPreferences().splashCustom) {
      rmSync(zaicodeSplashCustomDir(), { recursive: true, force: true });
      writeZaicodeLauncherPreferences({ splashCustom: false });
    }
    return readState();
  }
  if (typeof input.imagePath !== "string" || !input.imagePath.trim()) return readState();
  const bytes = readFileSync(input.imagePath);
  const ext = sniffImage(bytes);
  if (!ext) return readState();
  const dir = zaicodeSplashCustomDir();
  mkdirSync(dir, { recursive: true });
  const target = `custom.${ext}`;
  copyFileSync(input.imagePath, join(dir, target));
  writeFileSync(join(dir, "zaicode-splash.html"), SPLASH_PAGE(target), "utf8");
  writeZaicodeLauncherPreferences({ splashCustom: true });
  return readState();
}
