import { copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import {
  ZAICODE_SPLASH_PLACEHOLDER_PNG_BASE64,
  ZAICODE_SPLASH_PLACEHOLDER_SIZE,
  normalizeZaicodeSplashOptions,
  type ZaicodeSplashPrefsInput,
} from "@zcode/shared";

/**
 * File side of the custom start-up splash (SRC-049), kept free of `electron`
 * so it can be tested. zaicodeSplashPrefs.ts owns the settings and the page.
 *
 * SRC-058: exactly one `custom.<ext>` may exist. Three start-up surfaces read
 * the picture:
 * - the root launcher tries custom.png first, then jpg, jpeg, gif, webp, bmp;
 * - the generated page names the file it was written for;
 * - the settings preview took the first readdir match.
 * Before this change, replacing a PNG with a JPG left both files, so the
 * launcher kept showing the old picture while the app showed the new one.
 */

export const ZAICODE_CUSTOM_SPLASH_IMAGE = /^custom\.(png|jpg|jpeg|gif|webp|bmp)$/i;

/** The picture's real format by its magic bytes (never by its file name), or null. */
export function sniffZaicodeSplashImage(bytes: Buffer): string | null {
  if (bytes.length > 8 && bytes[0] === 0x89 && bytes[1] === 0x50) return "png";
  if (bytes.length > 3 && bytes[0] === 0xff && bytes[1] === 0xd8) return "jpg";
  if (bytes.subarray(0, 3).toString("latin1") === "GIF") return "gif";
  if (bytes.subarray(0, 4).toString("latin1") === "RIFF" && bytes.subarray(8, 12).toString("latin1") === "WEBP") return "webp";
  if (bytes.subarray(0, 2).toString("latin1") === "BM") return "bmp";
  return null;
}

/** The installed custom picture in `dir`, or null (also when `dir` does not exist). */
export function findZaicodeCustomSplashImage(dir: string): string | null {
  if (!existsSync(dir)) return null;
  const entry = readdirSync(dir).find((name) => ZAICODE_CUSTOM_SPLASH_IMAGE.test(name));
  return entry ? join(dir, entry) : null;
}

/**
 * Copies `sourcePath` into `dir` as the one custom picture and writes the page
 * for it. Any previous `custom.*` is removed first, whatever its format.
 * Returns the installed file name, or null when the source is not a supported
 * picture; in that case nothing in `dir` changes.
 */
export function installZaicodeCustomSplashImage(
  dir: string,
  sourcePath: string,
  page: (imageFile: string) => string,
): string | null {
  const ext = sniffZaicodeSplashImage(readFileSync(sourcePath));
  if (!ext) return null;
  mkdirSync(dir, { recursive: true });
  const target = `custom.${ext}`;
  for (const name of readdirSync(dir)) {
    if (ZAICODE_CUSTOM_SPLASH_IMAGE.test(name) && name !== target) rmSync(join(dir, name), { force: true });
  }
  copyFileSync(sourcePath, join(dir, target));
  writeFileSync(join(dir, "zaicode-splash.html"), page(target), "utf8");
  return target;
}

/**
 * The splash page, one template for the bundled picture
 * (build/zaicode-splash/splash.html, kept byte-identical by a test) and the
 * operator's own (generated beside it in userData/zaicode-splash/).
 *
 * SRC-060: the page fills whatever window it gets (the size is a setting) and
 * reads the rest from its query: `v` version, `fit` contain/cover/stretch,
 * `status` 0 hides the loading line. The picture is never drawn at its own
 * size, so a large or high-DPI picture is scaled into the box, not cropped.
 * SRC-062: until the picture is decoded (and when it cannot be read at all)
 * the page shows the SAIPEN emblem placeholder, centred at a whole-pixel
 * size, so the first frame is never a half-drawn or cut-off picture.
 */
export function zaicodeSplashPage(imageFile: string): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      http-equiv="Content-Security-Policy"
      content="default-src 'none'; img-src 'self' data:; style-src 'unsafe-inline'; script-src 'unsafe-inline'"
    />
    <title>ZAICODE</title>
    <!--
      ZAICODE start-up splash (SRC-048, SRC-049, SRC-060, SRC-062). Generated by
      zaicodeSplashPage() in packages/desktop/src/main/zaicodeSplashFiles.ts;
      do not edit by hand.
    -->
    <style>
      html,
      body {
        margin: 0;
        width: 100vw;
        height: 100vh;
        overflow: hidden;
        background: #1a1810;
        cursor: default;
        user-select: none;
        -webkit-app-region: drag;
      }
      #picture {
        display: block;
        width: 100vw;
        height: 100vh;
        object-fit: contain;
        visibility: hidden;
      }
      #picture.ready {
        visibility: visible;
      }
      #placeholder {
        position: fixed;
        left: 50%;
        top: 50%;
        width: ${ZAICODE_SPLASH_PLACEHOLDER_SIZE}px;
        height: ${ZAICODE_SPLASH_PLACEHOLDER_SIZE}px;
        margin: -${ZAICODE_SPLASH_PLACEHOLDER_SIZE / 2 + 8}px 0 0 -${ZAICODE_SPLASH_PLACEHOLDER_SIZE / 2}px;
        image-rendering: pixelated;
      }
      #placeholder.gone {
        display: none;
      }
      #status {
        position: fixed;
        left: 14px;
        right: 14px;
        bottom: 12px;
        height: 14px;
        display: flex;
        justify-content: space-between;
        gap: 8px;
        overflow: hidden;
        white-space: nowrap;
        font: 11px/14px "Verdana_m1", Verdana, sans-serif;
        color: #d4c89a;
        -webkit-font-smoothing: none;
      }
      #version {
        color: #9c9371;
      }
    </style>
  </head>
  <body>
    <img id="placeholder" src="data:image/png;base64,${ZAICODE_SPLASH_PLACEHOLDER_PNG_BASE64}" alt="" />
    <img id="picture" src="${imageFile}" alt="" />
    <div id="status"><span id="text">Starting ZAICODE…</span><span id="version">ZAICODE</span></div>
    <script>
      const query = new URLSearchParams(location.search);
      const version = query.get("v");
      if (version) document.getElementById("version").textContent = "ZAICODE " + version;
      const picture = document.getElementById("picture");
      const fit = query.get("fit");
      picture.style.objectFit = fit === "cover" ? "cover" : fit === "stretch" ? "fill" : "contain";
      if (query.get("status") === "0") document.getElementById("status").style.display = "none";
      // Whole-number scaling keeps pixel art crisp; any other factor is smoothed.
      const sharpen = () => {
        const factor = Math.min(innerWidth / picture.naturalWidth, innerHeight / picture.naturalHeight);
        picture.style.imageRendering = Number.isInteger(factor) ? "pixelated" : "auto";
      };
      // The picture replaces the placeholder only once it is fully decoded; a broken
      // or unreadable picture keeps the placeholder (SRC-062).
      const reveal = () => {
        if (!picture.naturalWidth) return;
        sharpen();
        const done = () => {
          picture.classList.add("ready");
          document.getElementById("placeholder").classList.add("gone");
        };
        if (picture.decode) picture.decode().then(done, () => undefined);
        else done();
      };
      if (picture.complete) reveal();
      else picture.addEventListener("load", reveal, { once: true });
      window.zaicodeSplashStatus = (text) => {
        document.getElementById("text").textContent = String(text);
      };
    </script>
  </body>
</html>
`;
}

/**
 * Validates what Settings sends. `imagePath` keeps its three meanings:
 * undefined = leave the picture alone, null = back to the bundled picture,
 * a string = install that file. SRC-060: the handler used to turn undefined
 * into null, so flipping the on/off switch deleted the custom picture.
 */
export function parseZaicodeSplashPrefsInput(input: unknown): ZaicodeSplashPrefsInput {
  if (!input || typeof input !== "object" || typeof (input as { enabled?: unknown }).enabled !== "boolean") {
    throw new TypeError("Expected splash preferences { enabled, imagePath?, options? }");
  }
  const { enabled, imagePath, options } = input as { enabled: boolean; imagePath?: unknown; options?: unknown };
  if (imagePath !== undefined && imagePath !== null && typeof imagePath !== "string") {
    throw new TypeError("Expected splash picture path or null");
  }
  const parsed: ZaicodeSplashPrefsInput = { enabled };
  if (imagePath !== undefined) parsed.imagePath = imagePath;
  if (options && typeof options === "object") {
    // Only the keys that were sent; each one is checked by the normalizer.
    const normalized = normalizeZaicodeSplashOptions(options);
    parsed.options = Object.fromEntries(
      Object.keys(normalized)
        .filter((key) => key in options)
        .map((key) => [key, normalized[key as keyof typeof normalized]]),
    );
  }
  return parsed;
}

/**
 * Rewrites an installed custom page when the template changed since it was
 * written (a page from before SRC-060 had a fixed 560x300 box and no fit).
 * Returns whether a custom picture is installed.
 */
export function refreshZaicodeCustomSplashPage(dir: string): boolean {
  const image = findZaicodeCustomSplashImage(dir);
  if (!image) return false;
  const page = join(dir, "zaicode-splash.html");
  const expected = zaicodeSplashPage(basename(image));
  try {
    if (!existsSync(page) || readFileSync(page, "utf8") !== expected) writeFileSync(page, expected, "utf8");
  } catch {
    return existsSync(page);
  }
  return true;
}
