import {
  AlertTriangle,
  Archive,
  ArrowLeftRight,
  BatteryCharging,
  Check,
  ChevronsDownUp,
  Clock,
  Copy,
  Cpu,
  Dot,
  FolderOpen,
  Grid3x3,
  Hand,
  HelpCircle,
  Keyboard,
  List,
  Mail,
  Move,
  Pencil,
  Pin,
  Play,
  Plus,
  RefreshCw,
  Save,
  Send,
  Settings,
  Star,
  StepForward,
  ToggleLeft,
  Undo2,
  Wrench,
  X,
  type LucideIcon,
} from "lucide-react";

/** The small icon in front of each row of the Sounds table, by the name the event list gives it. */
export const ZAICODE_SOUND_GLYPHS: Record<string, LucideIcon> = {
  check: Check,
  cross: X,
  question: HelpCircle,
  hand: Hand,
  dot: Dot,
  play: Play,
  plus: Plus,
  swap: ArrowLeftRight,
  box: Archive,
  undo: Undo2,
  pen: Pencil,
  pin: Pin,
  send: Send,
  step: StepForward,
  grid: Grid3x3,
  folder: FolderOpen,
  move: Move,
  list: List,
  fold: ChevronsDownUp,
  save: Save,
  engine: Cpu,
  wrench: Wrench,
  battery: BatteryCharging,
  warn: AlertTriangle,
  refresh: RefreshCw,
  clock: Clock,
  mail: Mail,
  gear: Settings,
  copy: Copy,
  key: Keyboard,
  toggle: ToggleLeft,
  star: Star,
};
